{
    "name": "cPanel Email & Domain Manager",
    "version": "18.0.1.1.0",
    "summary": "Manage cPanel mailboxes, domains, quotas and hosting usage",
    "category": "Administration",
    "author": "Alezdhar Company",
    "license": "LGPL-3",
    "depends": ["base", "mail", "hr"],
    "data": [
        "security/cpanel_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "data/cpanel_tag_data.xml",
        "data/cpanel_mailbox_template_data.xml",
        "wizard/cpanel_mailbox_wizard_views.xml",
        "views/cpanel_mailbox_views.xml",
        "views/cpanel_storage_views.xml",
        "views/cpanel_domain_views.xml",
        "views/cpanel_server_views.xml",
        "views/cpanel_log_views.xml",
        "views/cpanel_forwarder_views.xml",
        "views/cpanel_tag_views.xml",
        "views/cpanel_mailbox_template_views.xml",
        "views/res_users_views.xml",
        "views/cpanel_dashboard_views.xml",
        "views/cpanel_menus.xml",
    ],
    "application": True,
    "assets": {
        "web.assets_backend": [
            "cpanel_manager/static/src/js/mailbox_tag_multi_edit.js",
            "cpanel_manager/static/src/scss/dashboard.scss",
        ],
    },
    "installable": True,
}
