{
    'name': 'Invoice Company Letterhead',
    'version': '18.0.6.0.0',
    'summary': 'Multiple invoice designs, PDF letterheads and invoice preview',
    'category': 'Accounting/Accounting',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': ['account', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_company_views.xml',
        'views/invoice_letterhead_design_views.xml',
        'wizard/invoice_print_wizard_views.xml',
        'report/report_invoice.xml',
        'report/report_action.xml',
        'views/account_move_views.xml',
    ],
    'installable': True,
    'application': False,
}
