{
    "name": "Fast Financial Reporting",
    "version": "18.0.0.2.0",
    "category": "Accounting/Accounting",
    "summary": "Fast summarized financial reporting for very large Odoo accounting databases",
    "description": "Safe day-batched aggregation engine for posted accounting entries.",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["account", "analytic"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/financial_daily_summary_views.xml",
        "views/financial_monthly_summary_views.xml",
        "views/financial_sync_state_views.xml",
        "views/financial_report_config_views.xml",
        "views/financial_rebuild_job_views.xml",
        "wizard/financial_rebuild_wizard_views.xml",
        "views/menus.xml",
        "data/ir_cron.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
