{
    'name': 'Techrar Connector',
    'version': '18.0.5.0.1',
    'category': 'Integration',
    'summary': 'Techrar Platform API Integration for Odoo 18',
    'author': 'Ahmed Abo EL-Atta',
    'website': 'https://www.linkedin.com/in/ahmedaboelatta/',
    'depends': ['base', 'web', 'sale', 'contacts', 'stock', 'account', 'analytic'],
    'images': ['static/description/logo.png'],
    'assets': {
        'web.assets_backend': [
            'techrar_connector/static/src/js/techrar_dashboard.js',
            'techrar_connector/static/src/xml/techrar_dashboard.xml',
            'techrar_connector/static/src/scss/techrar_dashboard.scss',
        ],
    },
    'data': [
        'security/techrar_connector_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/techrar_branch_views.xml',
        'views/techrar_config_views.xml',
        'views/techrar_sync_log_views.xml',
        'views/techrar_webhook_event_views.xml',
        'views/techrar_sync_wizard_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
